server:
  port: 8000

spring:
  application:
    name: dwz
  datasource:
    url: jdbc:mysql://localhost:3306/jd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: l(=8gp_04h*&
    driver-class-name: com.mysql.cj.jdbc.Driver
    minPoolSize: 3
    maxPoolSize: 10
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    mainteanceInterval: 60
    maxIdleTime: 60

  ## Redis
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: 123654
    timeout: 3000
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:com/example/demo/dao/mapper/*.xml
#  type-aliases-package: com.example.entity

  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句
    map-underscore-to-camel-case: true #开启驼峰命名转换
  # mybatis使用分页插件
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql






